GET http://localhost:3000/beerstyles/

###

GET http://localhost:3000/beerstyles/627a4cdd9b995aeb952d0e3b

###

DELETE  http://localhost:3000/beerstyles/627cec7cde18e5531b0020cb

###

POST http://localhost:3000/beerstyles
Content-Type: application/json

{
  "styleGroup":	"Ale Style",
  "styleOrigin":	"Belgian and French Origin Categories",
  "category":	"Belgian Fruit Beer",
  "subCategory":	"Belgian-Style Fruit Beer",
  "perceivedMaltAromaAndFlavor":	"None to Medium-high",
  "perceivedHopAromaAndFlavor":	"Low to High",
  "perceivedBitterness":	"Various",
  "body":	"Various",
  "originalGravityPlato":	"7.6-25.9 °P",
  "finalGravityPlato":	"1.5-7.6 °P",
  "alcoholByVolume":	"2.5%-12.0%",
  "bitternessIbu":	"5-50",
  "colorSrm":	"10-100",
  "colorEbc":	"5-70",
  "fermentationCharacteristics":	"Acidic bacterial fermentation attributes may be absent or may be present; if present, such attributes contribute to acidity and enhance fruity balance.",
  "additionalNotes":	"Fruit aromas, ranging from subtle to intense, should be present and should not be overpowered by hop aromas. Belgian-Style Fruit Beers are fermented with traditional Belgian yeast, (Wit, Abbey, Farmhouse, etc.). Within the framework of these guidelines, coconut is deﬁned as a vegetable, and beers containing coconut should be categorized as Field Beers. Fruit or fruit extracts, used as adjuncts in either the mash, kettle, primary or secondary fermentation, provide harmonious fruit character ranging from subtle to intense. Classifying these beers can be complex. Wood vessels may be used for fermentation and aging, but wood-derived aromas and ﬂavors such as vanillin should not be present. Versions exhibiting attributes derived from wood or liquids previously aged in wood should be categorized in other Wood-Aged Beer categories."
}

###

PATCH http://localhost:3000/beerstyles/6276d14ad7070cd0e83e857c
Content-Type: application/json

{
  "styleGroup": 	"Hunters Beers!",
  "additionalNotes": 	"."

}
